# Для локальной разработки
version: "3.9"

services:

  elasticsearch:
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:8.12.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
